package com.coursemonitor.entity;
// Generated Feb 23, 2016 2:24:40 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.faces.convert.FacesConverter;

/**
 * CourseLeader generated by hbm2java
 */
@FacesConverter(forClass = CourseLeader.class)
public class CourseLeader implements java.io.Serializable {

    private int clId;
    private String clName;
    private Set courses = new HashSet(0);

    public CourseLeader() {
    }

    public CourseLeader(int clId) {
        this.clId = clId;
    }

    public CourseLeader(int clId, String clName, Set courses) {
        this.clId = clId;
        this.clName = clName;
        this.courses = courses;
    }

    public int getClId() {
        return this.clId;
    }

    public void setClId(int clId) {
        this.clId = clId;
    }

    public String getClName() {
        return this.clName;
    }

    public void setClName(String clName) {
        this.clName = clName;
    }

    public Set getCourses() {
        return this.courses;
    }

    public void setCourses(Set courses) {
        this.courses = courses;
    }

}
